### ISSUE TITLE
Andy Ko's CS Teaching presentation

### ISSUE THREAD

**Issue by acbart** [zamansky/awesome-cs-education#3]
I think adding a link to Andy Ko's blog is worth while, but I also think a specific link to this presentation he made seems worthwhile:

https://docs.google.com/presentation/d/1skkpIGPR81RsnIuth2PjhMkCi1YuODqpLOhEEjXsnXQ/edit

Any suggestions on how it should be categorized?

**Comment by zamansky** [comment]
I think adding the blog is certainly appropriate. I'm not sure about to a specific talk (even though I do agree with a number of things in the presentation).

Since the presentation is basically Andy's thoughts on how you should teach linking directly could be read as an implicit endorsement which means all of us (those who end up contributing) would have to agree with all of it and then maybe make a decision not to post other talks on the same subject.

I'm not sure on this. 

Maybe a section of "Interesting talks/lectures/videos/presentations" with a "we don't necessarily endorse all of the content but do feel it's worth a read or a view. 

What do you think?

**Comment by zamansky** [comment]
I added a section - let me know what you think (and feel free to issue a pull request with more stuff / edits etc).
