### ISSUE TITLE
creating a PD section?

### ISSUE THREAD

**Issue by jkeesh** [zamansky/awesome-cs-education#6]
Many teachers are interested in PD - creating a PD section could be helpful as well to include various resources, both online/offline and at different grade levels.

**Comment by zamansky** [comment]
I think a regional / recurring PD section is a great idea -- not sure about online stuff since pretty much all the learning sources are or can be PD resources and things could get ridiculous. 

What types of online specific PD things did you have in mind?

**Comment by jkeesh** [comment]
there actually aren't too many online CS PD courses? Which other ones do you know? I think there is a difference between something that is a resource for teaching CS vs. an actual professional development course. I think both online PD and regional PD could be good as a resource to add. Lots of the teachers who contact us are actually looking for PD courses

**Comment by zamansky** [comment]
Jeremy,

I wasn't familiar with online PD - the closest thing I've seen are some of
the coursera teacher Ed Moocs (which I think are pretty bogus).

My only concern is that I Don't want this just to become a listing for
courses that are just as likely that a student will take - I think it
should be specifically for teachers (since it's easy enough to link to
already existing lists of courses for learners).

How about put in the pull request

Mike


http://cestlaz.github.com
